services:
  web:
    image: yiisoftware/yii2-php:8.4-apache
    restart: unless-stopped
    ports:
      # 6000 на Windows часто занят MobaXterm (X11). Используйте 6001 в браузере.
      - "6001:80"
    volumes:
      - ./yii2:/app
    env_file:
      - ./yii2/.env
    environment:
      YII_ENV: ${YII_ENV:-dev}
      YII_DEBUG: ${YII_DEBUG:-1}

  static:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "6002:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
